import type { Ovino } from "../api/models/ovino/OvinoModel";

export const mockOvinos: Ovino[] = [
  {
    rfid: "01",
    nome: "Aurora",
    raca: "Dorper",
    fbb: "FBB001",
    dataNascimento: "2021-03-15",
    grauPureza: "100%",
    sexo: "Fêmea",
    status: "Ativo",
    imagem: "/imagens/ovinos/aurora.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "02",
    nome: "Zeus",
    raca: "Santa Inês",
    fbb: "FBB002",
    dataNascimento: "2020-07-10",
    grauPureza: "100%",
    sexo: "Macho",
    status: "Ativo",
    imagem: "/imagens/ovinos/zeus.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "03",
    nome: "Estrela",
    raca: "Dorper",
    fbb: "FBB003",
    dataNascimento: "2021-08-20",
    grauPureza: "75%",
    sexo: "Fêmea",
    status: "Ativo",
    imagem: "/imagens/ovinos/estrela.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "04",
    nome: "Apollo",
    raca: "Texel",
    fbb: "FBB004",
    dataNascimento: "2019-05-02",
    grauPureza: "100%",
    sexo: "Macho",
    status: "Ativo",
    imagem: "/imagens/ovinos/apollo.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "05",
    nome: "Luna",
    raca: "Santa Inês",
    fbb: "FBB005",
    dataNascimento: "2022-01-12",
    grauPureza: "50%",
    sexo: "Fêmea",
    status: "Ativo",
    imagem: "/imagens/ovinos/luna.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "06",
    nome: "Thor",
    raca: "Dorper",
    fbb: "FBB006",
    dataNascimento: "2020-09-09",
    grauPureza: "100%",
    sexo: "Macho",
    status: "Ativo",
    imagem: "/imagens/ovinos/thor.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "07",
    nome: "Íris",
    raca: "Texel",
    fbb: "FBB007",
    dataNascimento: "2021-06-18",
    grauPureza: "75%",
    sexo: "Fêmea",
    status: "Ativo",
    imagem: "/imagens/ovinos/iris.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "08",
    nome: "Poseidon",
    raca: "Santa Inês",
    fbb: "FBB008",
    dataNascimento: "2019-11-25",
    grauPureza: "100%",
    sexo: "Macho",
    status: "Ativo",
    imagem: "/imagens/ovinos/poseidon.jpg",
    rfidMae: undefined,
    rfidPai: undefined,
    idParto: undefined,
    idCompra: undefined,
  },
  // --- Filhos ---
  {
    rfid: "09",
    nome: "Hera",
    raca: "Dorper",
    fbb: "FBB009",
    dataNascimento: "2023-04-05",
    grauPureza: "50%",
    sexo: "Fêmea",
    status: "Ativo",
    imagem: "/imagens/ovinos/hera.jpg",
    rfidMae: "01", // Aurora
    rfidPai: "02",  // Zeus
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "10",
    nome: "Hermes",
    raca: "Texel",
    fbb: "FBB010",
    dataNascimento: "2023-07-22",
    grauPureza: "50%",
    sexo: "Macho",
    status: "Ativo",
    imagem: "/imagens/ovinos/hermes.jpg",
    rfidMae: "03", // Estrela
    rfidPai: "04",  // Apollo
    idParto: undefined,
    idCompra: undefined,
  },
  {
    rfid: "11",
    nome: "Afrodite",
    raca: "Santa Inês",
    fbb: "FBB011",
    dataNascimento: "2023-10-03",
    grauPureza: "50%",
    sexo: "Fêmea",
    status: "Ativo",
    imagem: "/imagens/ovinos/afrodite.jpg",
    rfidMae: "05", // Luna
    rfidPai: "06",  // Thor
    idParto: undefined,
    idCompra: undefined,
  },
];
